Repository UK-Export-Finance/mdm-api, pull requests merged in 2023-04, with the labels that each got.

#97 refactor: code refactor. + updated the documentation
  package-lock.json
  package.json
  src/modules/currencies/currencies.controller.ts
  src/modules/currencies/currencies.service.ts
  src/modules/currencies/dto/currency-exchange.dto.ts
  src/modules/currencies/dto/currency.dto.ts
  src/modules/currencies/entities/currency-exchange.entity.ts
  src/modules/currencies/entities/currency.entity.ts
  src/modules/interest-rates/entities/interest-rate.entity.ts
  src/modules/interest-rates/interest-rates.controller.ts
  src/modules/interest-rates/interest-rates.service.ts
  src/modules/markets/entities/market.entity.ts
  src/modules/markets/markets.controller.ts
  src/modules/numbers/entities/ukef-id.entity.ts
  src/modules/numbers/numbers.module.ts
  src/modules/numbers/numbers.service.ts
  src/modules/premium-schedules/entities/premium-schedule.entity.ts
  src/modules/sector-industries/entities/sector-industry.entity.ts
  src/modules/sector-industries/sector-industries.controller.ts
  src/modules/sector-industries/sector-industries.module.ts
  src/modules/sector-industries/sector-industries.service.ts
  src/modules/yield-rates/entities/yield-rate.entity.ts
  src/modules/yield-rates/yield-rates.controller.ts
Labels: Type: chore, Type: Docs, Type: Fix

#107 fix(APIM-197): fixed currency exchange issues
  src/modules/currencies/currencies.service.ts
  src/modules/currencies/entities/currency-exchange.entity.ts
  src/modules/markets/entities/market.entity.ts
  test/currencies/currencies.api-test.ts
Labels: Type: Fix

#113 fix: bug apim-203 make optional fields optional in spec
  src/modules/currencies/dto/currency-exchange.dto.ts
  src/modules/premium-schedules/dto/create-premium-schedule.dto.ts
  src/modules/yield-rates/dto/get-yield-rates-query.dto.ts
Labels: Type: Bug

#78 feat(APIM-162): API management instance
  .cspell.json
  .github/workflows/deploy.sh
  .github/workflows/development.yml
  .github/workflows/infrastructure.yml
  CHANGELOG.md
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/modules/constants/entities/constants-spi.entity.ts
  src/swagger.ts
Labels: Type: Feature, Type: Security, Infrastructure

#115 docs(gha): improved GHA documentation
  .env.sample
  .github/workflows/README.md
  .github/workflows/infrastructure.yml
  README.md
  docker-compose.yml
Labels: Type: Docs

#143 fix(revision): revision suffix to refer to run_id
  .github/workflows/development.yml
Labels: Type: Feature
