Repository UK-Export-Finance/mdm-api, pull requests merged in 2023-02, with the labels that each got.

#1 feat: add MDM databases, number generator, market and healthchecks
  .env.sample
  docker-compose.yml
  package-lock.json
  package.json
  src/config/database.config.ts
  src/database/index.ts
  src/database/mssql-cedar-database.module.ts
  src/database/mssql-cis-database.module.ts
  src/database/mssql-mdm-database.module.ts
  src/database/mssql-number-generator-database.module.ts
  src/database/redis-database.module.ts
  src/helpers/db-response.helper.ts
  src/helpers/validate-ukef-id.helpers.ts
  src/main.module.ts
  src/main.ts
  src/modules/bond-types/bond-types.controller.ts
  src/modules/bond-types/bond-types.module.ts
  src/modules/bond-types/bond-types.service.ts
  src/modules/bond-types/entities/bond-types.entity.ts
  src/modules/countries/entities/mdm-country.entity.ts
  src/modules/countries/mdm-countries.controller.ts
  src/modules/countries/mdm-countries.module.ts
  src/modules/countries/mdm-countries.service.ts
  src/modules/country/country.controller.ts
  src/modules/country/country.module.ts
  src/modules/country/country.service.ts
  src/modules/country/entities/country.entity.ts
  src/modules/credit-risk-rating/credit-risk-rating.controller.ts
  src/modules/credit-risk-rating/credit-risk-rating.module.ts
  src/modules/credit-risk-rating/credit-risk-rating.service.ts
  src/modules/credit-risk-rating/entities/credit-risk-rating.entity.ts
  src/modules/healthcheck/healthcheck.controller.ts
  src/modules/healthcheck/healthcheck.module.ts
  src/modules/healthcheck/healthcheck.service.ts
  src/modules/markets/entities/market.entity.ts
  src/modules/markets/markets.controller.ts
  src/modules/markets/markets.module.ts
  src/modules/markets/markets.service.ts
  src/modules/mdm.module.ts
  src/modules/numbers/dto/create-ukef-id.dto.ts
  src/modules/numbers/entities/number-type.entity.ts
  src/modules/numbers/entities/ukef-id.entity.ts
  src/modules/numbers/number-types.controller.ts
  src/modules/numbers/number-types.service.ts
  src/modules/numbers/numbers.controller.ts
  src/modules/numbers/numbers.module.ts
  src/modules/numbers/numbers.service.ts
Labels: enhancement

#11 feat: added `cspell`, custom paths, lint staged files & updated all npm packages
  .cspell.json
  .env.sample
  .eslintrc.js
  .eslintrc.json
  .husky/commit-msg
  .lintstagedrc.json
  README.md
  nest-cli.json
  package-lock.json
  package.json
  src/config/index.ts
  src/database/index.ts
  src/helpers/transform-interceptor.helper.ts
  src/helpers/validate-ukef-id.helper.ts
  src/main.module.ts
  src/main.ts
  src/modules/healthcheck/healthcheck.controller.ts
  src/modules/healthcheck/healthcheck.module.ts
  src/modules/healthcheck/healthcheck.service.ts
  src/modules/markets/entities/market.entity.ts
  src/modules/markets/markets.controller.ts
  src/modules/markets/markets.module.ts
  src/modules/markets/markets.service.ts
  src/modules/mdm.module.ts
  src/modules/numbers/dto/create-ukef-id.dto.ts
  src/modules/numbers/number-types.controller.ts
  src/modules/numbers/number-types.service.ts
  src/modules/numbers/numbers.controller.ts
  src/modules/numbers/numbers.module.ts
  src/modules/numbers/numbers.service.ts
  src/swagger.ts
  tsconfig.eslint.json
  tsconfig.json
Labels: Type: Feature

#10 feat: added tests for GET `/markets`
  package.json
  src/config/app.config.ts
  src/database/mssql-cedar-database.module.ts
  src/database/mssql-cis-database.module.ts
  src/database/mssql-mdm-database.module.ts
  src/database/mssql-number-generator-database.module.ts
  src/modules/markets/dto/markets-query.dto.ts
  src/modules/markets/dto/query-param-active-enum.ts
  src/modules/markets/markets.controller.ts
  src/modules/markets/markets.service.ts
  test/api.js
  test/app.api-test.ts
  test/app.e2e-spec.ts
  test/createApp.ts
  test/jest.api-test.json
  test/markets/expected-responses/GET-markets-query-active-N.json
  test/markets/expected-responses/GET-markets-query-active-Y.json
  test/markets/expected-responses/GET-markets.json
  test/markets/markets.api-test.ts
Labels: Type: Feature

#13 chore: updated the `healthcheck` endpoints
  docker-compose.yml
  package-lock.json
  package.json
  src/modules/healthcheck/healthcheck.controller.ts
  src/modules/healthcheck/healthcheck.module.ts
  src/modules/healthcheck/healthcheck.service.ts
  src/modules/markets/dto/markets-query.dto.ts
  src/modules/markets/dto/query-param-active-enum.ts
  src/modules/markets/entities/market.entity.ts
  src/modules/markets/markets.controller.ts
Labels: Type: Chore

#14 fix: added path aliases to jest api tests, fixed spelling
  .cspell.json
  test/jest.api-test.json
  test/markets/expected-responses/GET-markets-query-active-N.json
  test/markets/expected-responses/GET-markets-query-active-Y.json
  test/markets/expected-responses/GET-markets.json
Labels: Type: Fix

#18 chore(npm-update): Package updates
  package-lock.json
  package.json
Labels: Type: Chore

#17 feat(API-69): added `/interest-rates` endpoint
  .cspell.json
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  src/modules/interest-rates/entities/interest-rate.entity.ts
  src/modules/interest-rates/interest-rates.controller.spec.ts
  src/modules/interest-rates/interest-rates.controller.ts
  src/modules/interest-rates/interest-rates.module.ts
  src/modules/interest-rates/interest-rates.service.ts
  src/modules/mdm.module.ts
  test/api.ts
  test/app.api-test.ts
  test/interest-rates/interest-rates.api-test.ts
  test/markets/markets.api-test.ts
  test/numbers/numbers.api-test.ts
  tsconfig.json
Labels: Type: Feature

#21 feat(API-82): Improved GHA
  .github/workflows/dependency-review.yml
  .github/workflows/deploy.sh
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/sca.yml
Labels: Type: Feature

#25 fix: remove GET /number-types endpoint, its not used by clients
  src/modules/numbers/entities/number-type.entity.ts
  src/modules/numbers/number-types.controller.ts
  src/modules/numbers/number-types.service.ts
  src/modules/numbers/numbers.module.ts
  test/numbers/expected-responses/GET-number-types.json
  test/numbers/numbers.api-test.ts
Labels: Type: Fix

#20 feat: ensure new ids are in order
  .github/workflows/lint.yml
  src/modules/numbers/entities/ukef-id.entity.ts
  src/modules/numbers/numbers.service.spec.ts
  src/modules/numbers/numbers.service.ts
  test/numbers/numbers.api-test.ts
Labels: Type: Feature, Type: Fix

#27 feat: make markets API tests more generic
  test/markets/expected-responses/GET-markets-query-active-N.json
  test/markets/expected-responses/GET-markets-query-active-Y.json
  test/markets/expected-responses/GET-markets.json
  test/markets/markets.api-test.ts
  test/numbers/expected-responses/GET-markets-query-active-N.json
  test/numbers/expected-responses/GET-markets.json
  test/numbers/expected-responses/GET-numbers-query-type-1-and-ukefId-0030581069.json
  test/numbers/numbers.api-test.ts
Labels: Type: Chore

#28 feat(unit-test): Unit testing on GHA
  .github/workflows/sca.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: Type: Feature

#30 feat: added GET `/sector-industries` endpoint
  src/modules/interest-rates/interest-rates.controller.ts
  src/modules/mdm.module.ts
  src/modules/numbers/numbers.service.ts
  src/modules/sector-industries/dto/get-sector-industries-query.dto.ts
  src/modules/sector-industries/entities/sector-industry.entity.ts
  src/modules/sector-industries/sector-industries.controller.test.ts
  src/modules/sector-industries/sector-industries.controller.ts
  src/modules/sector-industries/sector-industries.module.ts
  src/modules/sector-industries/sector-industries.service.ts
  test/sector-industries/sector-industries.api-test.ts
Labels: Type: Feature

#34 feat(API-97): Centralised constants
  .eslintrc.json
  .husky/commit-msg
  jest.config.ts
  src/constants/date.ts
  src/constants/index.ts
  src/main.module.ts
  src/main.ts
  src/modules/healthcheck/healthcheck.module.ts
  src/modules/interest-rates/interest-rates.service.ts
  src/modules/markets/entities/market.entity.ts
  src/modules/markets/markets.service.ts
  src/modules/mdm.module.ts
  src/modules/sector-industries/sector-industries.service.ts
  tsconfig.json
Labels: Type: Feature

#38 feat(API-83): GET `/constants/spi`
  .cspell.json
  src/modules/constants/constants.controller.test.ts
  src/modules/constants/constants.controller.ts
  src/modules/constants/constants.module.ts
  src/modules/constants/constants.service.ts
  src/modules/constants/dto/get-constants-spi-query.dto.ts
  src/modules/constants/entities/constants-spi.entity.ts
  src/modules/interest-rates/interest-rates.controller.ts
  src/modules/mdm.module.ts
  src/modules/numbers/numbers.controller.ts
  src/modules/numbers/numbers.service.test.ts
  src/modules/sector-industries/sector-industries.controller.ts
  test/constants/constants.spi.api-test.ts
Labels: Type: Feature

#39 feat: new endpoint GET /exposure-period
  src/modules/exposure-period/dto/exposure-period.dto.ts
  src/modules/exposure-period/dto/get-exposure-period-query.dto.ts
  src/modules/exposure-period/exposure-period.controller.test.ts
  src/modules/exposure-period/exposure-period.controller.ts
  src/modules/exposure-period/exposure-period.module.ts
  src/modules/exposure-period/exposure-period.service.ts
  src/modules/mdm.module.ts
  test/constants/constants.spi.api-test.ts
  test/exposure-period/exposure-period.api-test.ts
Labels: Type: Feature

#40 feat: added GET `/currencies`, `/currencies/{isoCode}` and `/currencies/exchange` endpoints
  package-lock.json
  package.json
  src/constants/database-name.constant.ts
  src/constants/date.constant.ts
  src/constants/index.ts
  src/database/mssql-cedar-database.module.ts
  src/database/mssql-cis-database.module.ts
  src/database/mssql-mdm-database.module.ts
  src/database/mssql-number-generator-database.module.ts
  src/main.ts
  src/modules/constants/constants.module.ts
  src/modules/constants/constants.service.ts
  src/modules/currencies/currencies.controller.test.ts
  src/modules/currencies/currencies.controller.ts
  src/modules/currencies/currencies.module.ts
  src/modules/currencies/currencies.service.ts
  src/modules/currencies/dto/currency-exchange.dto.ts
  src/modules/currencies/dto/currency.dto.ts
  src/modules/currencies/dto/index.ts
  src/modules/currencies/entities/currency-exchange.entity.ts
  src/modules/currencies/entities/currency.entity.ts
  src/modules/exposure-period/exposure-period.service.ts
  src/modules/healthcheck/healthcheck.controller.ts
  src/modules/interest-rates/interest-rates.module.ts
  src/modules/interest-rates/interest-rates.service.ts
  src/modules/markets/markets.module.ts
  src/modules/markets/markets.service.ts
  src/modules/mdm.module.ts
  src/modules/numbers/numbers.controller.ts
  src/modules/numbers/numbers.service.ts
  src/modules/sector-industries/sector-industries.service.ts
  test/currencies/currencies.api-test.ts
Labels: Type: Feature

#41 chore(deps): updated all NPM packages
  package-lock.json
  package.json
Labels: Type: Chore
