Repository UK-Export-Finance/mdm-api, pull requests merged in 2023-05, with the labels that each got.

#151 feat(staging): staging environment deployment
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
Labels: Type: Feature

#152 fix(deployment): generic deployment script
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  .husky/commit-msg
  package-lock.json
Labels: Infrastructure

#159 fix: lint fixes based on sonarcloud
  .dockerignore
  Dockerfile
  src/main.ts
  src/modules/constants/constants.controller.test.ts
  src/modules/currencies/currencies.controller.test.ts
  src/modules/exposure-period/exposure-period.controller.test.ts
  src/modules/exposure-period/exposure-period.service.ts
  src/modules/interest-rates/interest-rates.controller.test.ts
  src/modules/premium-schedules/premium-schedules.controller.test.ts
  src/modules/sector-industries/sector-industries.controller.test.ts
  src/modules/yield-rates/yield-rates.controller.test.ts
Labels: Type: Fix

#172 refactor(iac): iac refactored
  .github/workflows/deploy.sh
  .github/workflows/deployment.yml
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
Labels: Infrastructure

#173 fix(iac): added missing argument
  .github/workflows/deployment.yml
Labels: Infrastructure

#176 Revert "fix(mdm): reverted commit 5e1d74 (#174)"
  .dockerignore
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
  Dockerfile
  README.md
  src/main.ts
  src/modules/constants/constants.controller.test.ts
  src/modules/currencies/currencies.controller.test.ts
  src/modules/exposure-period/exposure-period.controller.test.ts
  src/modules/exposure-period/exposure-period.service.ts
  src/modules/interest-rates/interest-rates.controller.test.ts
  src/modules/premium-schedules/premium-schedules.controller.test.ts
  src/modules/sector-industries/sector-industries.controller.test.ts
  src/modules/yield-rates/yield-rates.controller.test.ts
Labels: Type: Fix, Infrastructure

#206 feat(eslint): added destructure eslint rule
  .eslintrc.json
  src/modules/premium-schedules/premium-schedules.service.ts
Labels: Type: Feature

#207 feat(APIM-261): individual database hosts
  .env.sample
  .github/workflows/deployment.yml
  docker-compose.yml
  src/config/database.config.ts
Labels: Type: chore, Type: Feature

#210 feat(APIM-261): API import post deployment
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  package-lock.json
  src/modules/healthcheck/healthcheck.controller.ts
Labels: Type: Feature

#218 fix(APIM-207): Iac Monitor
  .github/workflows/deployment.yml
Labels: Infrastructure

#220 docs(cicd): updated documentation + deps bump
  .github/workflows/README.md
  .github/workflows/deploy.sh
  .github/workflows/deployment.yml
  package-lock.json
  package.json
Labels: Infrastructure
