Repository UK-Export-Finance/mdm-api, pull requests merged in 2023-07, with the labels that each got.

#299 fix(env): environment variable update
  .env.sample
  package-lock.json
  package.json
Labels: Infrastructure

#330 chore(deps): docker node update
  Dockerfile
  package-lock.json
  package.json
Labels: Type: Security

#332 chore(dockerfile): version updates
  Dockerfile
  docker-compose.yml
Labels: Type: Security

#343 fix(iac): ACR
  .github/workflows/deploy.sh
  package-lock.json
Labels: Infrastructure

#350 chore(deps): dependencies updates
  .github/dependabot.yml
  .github/workflows/deploy.sh
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
  .gitignore
  package-lock.json
  package.json
Labels: Type: chore

#324 feat(APIM-344): handle sensitive details in log messages
  .env.sample
  .github/workflows/deployment.yml
  docker-compose.yml
  package-lock.json
  package.json
  src/config/app.config.test.ts
  src/config/app.config.ts
  src/constants/index.ts
  src/constants/redact-strings-paths.constant.ts
  src/constants/redact-strings.constant.ts
  src/helpers/redact-strings-in-log-args.helper.test.ts
  src/helpers/redact-strings-in-log-args.helper.ts
  src/logging/build-key-to-redact.test.ts
  src/logging/build-key-to-redact.ts
  src/logging/console-logger-with-redact.test.ts
  src/logging/console-logger-with-redact.ts
  src/logging/log-keys-to-redact.test.ts
  src/logging/log-keys-to-redact.ts
  src/logging/logging-interceptor.helper.ts
  src/main.module.ts
  src/main.ts
  src/modules/auth/strategy/api-key.strategy.ts
  src/modules/constants/constants.service.ts
  src/modules/currencies/currencies.service.ts
  src/modules/exposure-period/exposure-period.service.ts
  src/modules/http/http.constants.ts
  src/modules/informatica/exception/informatica.exception.ts
  src/modules/informatica/informatica.module.ts
  src/modules/interest-rates/interest-rates.service.ts
  src/modules/markets/markets.service.ts
  src/modules/numbers/numbers.service.test.ts
  src/modules/numbers/numbers.service.ts
  src/modules/premium-schedules/premium-schedules.service.ts
  src/modules/sector-industries/sector-industries.service.ts
  src/modules/yield-rates/yield-rates.service.ts
  test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
Labels: Type: Feature

#357 feat(APIM-468): change how integer config values are parsed
  src/config/app.config.test.ts
  src/config/app.config.ts
  src/config/informatica.config.ts
  src/helpers/get-int-config.helper.test.ts
  src/helpers/get-int-config.ts
  src/helpers/regex.helper.test.ts
  test/common-tests/environment-variable-parsing-unit-tests.ts
Labels: Type: Feature

#364 fix(gitignore): environment variable introduction
  .env.sample
  .github/workflows/deployment.yml
  .gitignore
  docker-compose.yml
  package-lock.json
  package.json
Labels: Infrastructure
