Repository UK-Export-Finance/mdm-api, pull requests merged in 2023-03, with the labels that each got.

#47 chore(npm-update): dependencies update
  package-lock.json
Labels: Type: Chore

#44 feat: added authentication using API Key
  .env.sample
  README.md
  jest.config.ts
  package-lock.json
  package.json
  src/app.ts
  src/config/app.config.ts
  src/constants/auth.constant.ts
  src/constants/index.ts
  src/database/index.ts
  src/main.module.ts
  src/main.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.test.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/guard/api-key.guard.ts
  src/modules/auth/strategy/api-key.strategy.ts
  src/modules/database/database.module.ts
  src/modules/database/mssql-cedar-database.module.ts
  src/modules/database/mssql-cis-database.module.ts
  src/modules/database/mssql-mdm-database.module.ts
  src/modules/database/mssql-number-generator-database.module.ts
  src/modules/healthcheck/healthcheck.module.ts
  src/modules/mdm.module.ts
  src/swagger.ts
  test/markets/markets.api-test.ts
  test/numbers/numbers.api-test.ts
  tsconfig.json
Labels: Type: Feature, Type: Security

#45 feat(APIM-90-91): post and get premium schedules
  .cspell.json
  .eslintrc.json
  src/modules/mdm.module.ts
  src/modules/numbers/numbers.controller.ts
  src/modules/premium-schedules/dto/create-premium-schedule.dto.ts
  src/modules/premium-schedules/dto/get-premium-schedule-param.dto.ts
  src/modules/premium-schedules/entities/premium-schedule.entity.ts
  src/modules/premium-schedules/premium-schedules.controller.test.ts
  src/modules/premium-schedules/premium-schedules.controller.ts
  src/modules/premium-schedules/premium-schedules.module.ts
  src/modules/premium-schedules/premium-schedules.service.ts
  test/premium-schedules/premium-schedules.api-test.ts
Labels: Type: Feature

#49 feat(APIM-151): global enum introduction
  .env.sample
  src/constants/enums.ts
  src/constants/enums/products.ts
  src/constants/index.ts
  src/constants/products.ts
  src/modules/exposure-period/dto/get-exposure-period-query.dto.ts
  src/modules/premium-schedules/dto/create-premium-schedule.dto.ts
  test/exposure-period/exposure-period.api-test.ts
  test/premium-schedules/premium-schedules.api-test.ts
Labels: Type: Feature

#50 feat(APIM-96): added GET `/yield-rates` endpoint
  .cspell.json
  src/constants/date.constant.ts
  src/modules/constants/constants.controller.ts
  src/modules/constants/dto/get-constants-spi-query.dto.ts
  src/modules/currencies/currencies.controller.ts
  src/modules/currencies/dto/currency-exchange.dto.ts
  src/modules/currencies/dto/currency.dto.ts
  src/modules/exposure-period/dto/get-exposure-period-query.dto.ts
  src/modules/exposure-period/exposure-period.controller.ts
  src/modules/exposure-period/exposure-period.service.ts
  src/modules/markets/dto/markets-query.dto.ts
  src/modules/markets/markets.controller.ts
  src/modules/mdm.module.ts
  src/modules/numbers/dto/get-numbers-query.dto.ts
  src/modules/numbers/numbers.controller.ts
  src/modules/premium-schedules/premium-schedules.controller.ts
  src/modules/premium-schedules/premium-schedules.service.ts
  src/modules/sector-industries/dto/get-sector-industries-query.dto.ts
  src/modules/sector-industries/sector-industries.controller.ts
  src/modules/yield-rates/dto/get-yield-rates-query.dto.ts
  src/modules/yield-rates/entities/yield-rate.entity.ts
  src/modules/yield-rates/yield-rates.controller.test.ts
  src/modules/yield-rates/yield-rates.controller.ts
  src/modules/yield-rates/yield-rates.module.ts
  src/modules/yield-rates/yield-rates.service.ts
  test/exposure-period/exposure-period.api-test.ts
  test/yield-rates/yield-rates.api-test.ts
Labels: Type: Feature

#51 chore(deps): update all NPM packages
  commitlint.config.js
  package-lock.json
  package.json
  src/swagger.ts
Labels: Type: Chore

#57 chore(npm-update): dependency update
  package-lock.json
Labels: Type: Chore

#61 fix(CVE-2023-28154): webpack updated to 5.76.2
  package-lock.json
Labels: Type: Fix, Type: Security

#58 feat(APIM-149): APIM IaC
  .cspell.json
  .dockerignore
  .env.sample
  .github/workflows/deploy.sh
  .github/workflows/development.yml
  .github/workflows/infrastructure.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .npmrc
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  src/config/database.config.ts
  tsconfig.build.json
Labels: Type: Feature, Infrastructure

#71 feat(dependabot): added dependabot.yml GHA
  .github/dependabot.yml
Labels: Type: Feature, Type: Security

#82 feat: adding authentication header to swagger ui, removing wrong auth…
  src/modules/constants/constants.controller.ts
  src/modules/currencies/currencies.controller.ts
  src/modules/exposure-period/exposure-period.controller.ts
  src/modules/healthcheck/healthcheck.controller.ts
  src/modules/markets/markets.controller.ts
  src/modules/numbers/numbers.controller.ts
  src/swagger.ts
Labels: Type: Feature
