Repository UK-Export-Finance/mdm-api, pull requests merged in 2024-12, with the labels that each got.

#1082 fix(APIM-608): make GovNotify properties optional
  package-lock.json
  package.json
  src/helper-modules/govuk-notify/dto/post-emails-response.dto.ts
Labels: Type: Fix

#1097 chore(deps): dependencies updates
  .github/workflows/deployment.yml
  .github/workflows/github.yml
  .github/workflows/lint.yml
  .github/workflows/pr.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/helper-modules/govuk-notify/govuk-notify.service.test.ts
  src/helper-modules/ordnance-survey/ordnance-survey.service.test.ts
  test/companies/get-company-by-registration-number.api-test.ts
  test/support/generator/post-emails-generator.ts
Labels: Type: chore

#1090 feat(APIM-610): markets - add country rating description field
  src/modules/markets/entities/market.entity.ts
  test/markets/markets.api-test.ts
Labels: Type: Feature

#1089 feat(APIM-609): companies house - extend returned fields
  package-lock.json
  package.json
  src/helper-modules/companies-house/dto/get-company-companies-house-response.dto.ts
  src/modules/companies/companies.service.ts
  src/modules/companies/dto/get-company-response.dto.ts
  src/modules/companies/examples/example-response-for-get-company-by-registration-number.json
  test/support/generator/get-company-generator.ts
  test/support/generator/random-value-generator.ts
Labels: Type: chore, Type: Feature

#1083 feat(APIM-608): gov notify - file upload/link support
  package-lock.json
  package.json
  src/constants/govuk-notify.constant.ts
  src/helper-modules/govuk-notify/examples/example-response-for-prepare-upload.json
  src/helper-modules/govuk-notify/examples/example-response-for-send-emails.json
  src/helper-modules/govuk-notify/govuk-notify.service.test.ts
  src/helper-modules/govuk-notify/govuk-notify.service.ts
  src/modules/emails/dto/post-emails-request.dto.ts
Labels: Type: chore, Type: Feature

#1113 fix(APIM-611): notify, companies house bug fixes
  package-lock.json
  src/app.ts
  src/constants/govuk-notify.constant.ts
  src/helper-modules/companies-house/dto/get-company-companies-house-response.dto.ts
  src/main.ts
  src/modules/companies/companies.service.ts
  src/modules/companies/dto/get-company-response.dto.ts
  src/modules/emails/dto/post-emails-request.dto.ts
Labels: Type: Fix

#1114 chore(main): release 1.22.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#1119 chore(main): release 1.22.2
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
