Repository UK-Export-Finance/mdm-api, pull requests merged in 2024-05, with the labels that each got.

#804 feat(DTFS-7052): added GET `/geospatial/addresses/postcode` endpoint for Ordnance Survey API data
  .cspell.json
  .env.sample
  .eslintrc.json
  README.md
  docker-compose.yml
  jest.config.ts
  package-lock.json
  package.json
  src/config/index.ts
  src/config/informatica.config.test.ts
  src/config/informatica.config.ts
  src/config/ordnance-survey.config.test.ts
  src/config/ordnance-survey.config.ts
  src/constants/enums.ts
  src/constants/enums/geospatialCountries.ts
  src/constants/geospatial.constant.ts
  src/constants/index.ts
  src/helper-modules/ordnance-survey/dto/get-addresses-ordnance-survey-response.dto.ts
  src/helper-modules/ordnance-survey/dto/ordnance-survey-auth-error-response.dto.ts
  src/helper-modules/ordnance-survey/examples/example-response-for-search-places-v1-postcode-no-results.json
  src/helper-modules/ordnance-survey/examples/example-response-for-search-places-v1-postcode.json
  src/helper-modules/ordnance-survey/exception/ordnance-survey.exception.test.ts
  src/helper-modules/ordnance-survey/exception/ordnance-survey.exception.ts
  src/helper-modules/ordnance-survey/ordnance-survey.module.ts
  src/helper-modules/ordnance-survey/ordnance-survey.service.test.ts
  src/helper-modules/ordnance-survey/ordnance-survey.service.ts
  src/modules/geospatial/dto/get-addresses-by-postcode-query.dto.ts
  src/modules/geospatial/dto/get-addresses-response.dto.ts
  src/modules/geospatial/geospatial.controller.test.ts
  src/modules/geospatial/geospatial.controller.ts
  src/modules/geospatial/geospatial.module.ts
  src/modules/geospatial/geospatial.service.test.ts
  src/modules/geospatial/geospatial.service.ts
  src/modules/mdm.module.ts
  test/api.ts
  test/app.api-test.ts
  test/createApp.ts
  test/currencies/currencies.api-test.ts
  test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
  test/exposure-period/exposure-period.api-test.ts
  test/geospatial/get-address-by-postcode.api-test.ts
  test/interest-rates/interest-rates.api-test.ts
  test/markets/markets.api-test.ts
  test/numbers/numbers.api-test.ts
  test/premium-schedules/premium-schedules.api-test.ts
  test/sector-industries/sector-industries.api-test.ts
  test/support/api.ts
  test/support/environment-variables.ts
  test/support/generator/get-geospatial-addresses-generator.ts
  test/support/generator/random-value-generator.ts
  test/yield-rates/yield-rates.api-test.ts
  tsconfig.json
Labels: Type: chore, Type: Feature

#844 chore(deps): dependencies updates
  package-lock.json
  package.json
Labels: Type: chore

#887 chore(deps): dependencies updates
  .github/workflows/publish.yml
  package-lock.json
  package.json
Labels: Type: chore, Type: Fix

#889 chore(main): release 1.18.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#888 fix(deps): upgrade pino-http to 10.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Type: chore

#890 chore(main): release 1.19.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#891 fix(release-please): changed to GitHub plugin
  .github/workflows/publish.yml
Labels: Type: Fix

#892 chore(main): release 1.20.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#905 fix(eslint): reverted back to eslint `8.57.0`
  .cspell.json
  package-lock.json
  package.json
Labels: Type: Fix

#820 feat(DTFS-7049): added POST /emails endpoint for sending emails using GOV.UK Notify service
  .cspell.json
  package-lock.json
  package.json
  src/app.ts
  src/constants/govuk-notify.constant.ts
  src/constants/index.ts
  src/helper-modules/govuk-notify/dto/post-emails-response.dto.ts
  src/helper-modules/govuk-notify/examples/example-response-for-send-emails.json
  src/helper-modules/govuk-notify/govuk-notify.module.ts
  src/helper-modules/govuk-notify/govuk-notify.service.test.ts
  src/helper-modules/govuk-notify/govuk-notify.service.ts
  src/modules/emails/dto/post-emails-request.dto.ts
  src/modules/emails/emails.controller.test.ts
  src/modules/emails/emails.controller.ts
  src/modules/emails/emails.module.ts
  src/modules/emails/emails.service.test.ts
  src/modules/emails/emails.service.ts
  src/modules/geospatial/geospatial.controller.test.ts
  src/modules/geospatial/geospatial.service.test.ts
  src/modules/mdm.module.ts
  src/modules/numbers/dto/get-numbers-query.dto.ts
  test/common-tests/request-field-validation-api-tests/email-address-field-validation-api-tests.ts
  test/common-tests/request-field-validation-api-tests/object-field-validation-api-tests.ts
  test/common-tests/request-field-validation-api-tests/partials/require-validation.ts
  test/common-tests/request-field-validation-api-tests/partials/type-validation.ts
  test/common-tests/request-field-validation-api-tests/string-field-validation-api-tests.ts
  test/customers/get-customers.api-test.ts
  test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
  test/emails/post-emails.api-test.ts
  test/geospatial/get-address-by-postcode.api-test.ts
  test/support/api.ts
  test/support/generator/post-emails-generator.ts
  test/support/generator/random-value-generator.ts
  test/support/helpers/request-field-validation-helper.test.ts
  test/support/helpers/request-field-validation-helper.ts
Labels: Type: chore, Type: Feature
