Repository UK-Export-Finance/mdm-api, pull requests merged in 2025-08, with the labels that each got.

#1484 feat(GIFT-13654): get/map DOM business centre non-working days
  src/constants/business-centre.constant.ts
  src/constants/companies.constant.ts
  src/constants/customers.constant.ts
  src/constants/deals.constant.ts
  src/constants/dom.constant.ts
  src/constants/examples/examples.constant.ts
  src/constants/geospatial.constant.ts
  src/constants/govuk-notify.constant.ts
  src/constants/index.ts
  src/constants/ods.constant.ts
  src/helper-modules/govuk-notify/dto/post-emails-response.dto.ts
  src/helper-modules/govuk-notify/govuk-notify.service.ts
  src/helper-modules/ordnance-survey/ordnance-survey.service.test.ts
  src/helpers/map-business-centre-non-working-days.test.ts
  src/helpers/map-business-centre-non-working-days.ts
  src/helpers/regex.helper.ts
  src/modules/companies/dto/get-company-by-registration-number-query.dto.ts
  src/modules/customers/customers.controller.test.ts
  src/modules/customers/customers.service.ts
  src/modules/customers/dto/get-customers-query.dto.ts
  src/modules/dom/dom.controller.test.ts
  src/modules/dom/dom.controller.ts
  src/modules/dom/dom.service.test.ts
  src/modules/dom/dom.service.ts
  src/modules/dom/dto/get-dom-business-centre-non-working-day-mapped-response.dto.ts
  src/modules/dom/dto/get-dom-business-centre-non-working-days-param.dto.ts
  src/modules/dom/dto/get-dom-business-centre-param.dto.ts
  src/modules/dom/dto/get-dom-business-centre-response.dto.ts
  src/modules/dom/dto/index.ts
  src/modules/emails/dto/post-emails-request.dto.ts
  src/modules/emails/emails.controller.ts
  src/modules/emails/emails.service.ts
  src/modules/geospatial/dto/get-addresses-by-postcode-query.dto.ts
  src/modules/geospatial/dto/get-addresses-response.dto.ts
  src/modules/geospatial/geospatial.controller.test.ts
  src/modules/ods/dto/get-ods-business-centre-mapped-response.dto.ts
  src/modules/ods/dto/get-ods-business-centre-non-working-day-response.dto.ts
  src/modules/ods/dto/get-ods-business-centre-non-working-days-param.dto.ts
  src/modules/ods/dto/get-ods-business-centre-response.dto.ts
  src/modules/ods/dto/get-ods-customer-param.dto.ts
  src/modules/ods/dto/get-ods-deal-param.dto.ts
  src/modules/ods/dto/get-ods-deal-response.dto.ts
  src/modules/ods/dto/index.ts
  src/modules/ods/ods.controller.test.ts
  src/modules/ods/ods.controller.ts
  src/modules/ods/ods.service-findBusinessCentreNonWorkingDays.test.ts
  src/modules/ods/ods.service-findCustomer.test.ts
  src/modules/ods/ods.service-findDeal.test.ts
  src/modules/ods/ods.service.test.ts
  src/modules/ods/ods.service.ts
  src/modules/salesforce/salesforce.service.test.ts
  test/dom/dom.business-centres.api-test.ts
  test/geospatial/get-address-by-postcode.api-test.ts
  test/ods/ods.business-centres.api-test.ts
Labels: Type: chore, Type: Feature

#1473 chore(main): release 1.28.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#1504 chore(main): release 1.29.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#1518 chore(deps): dependencies updates
  package-lock.json
  package.json
Labels: Type: chore
