Repository UK-Export-Finance/mdm-api, pull requests merged in 2025-02, with the labels that each got.

#1182 chore(APIM-612): companies house - isactive field
  src/constants/companies.constant.ts
  src/modules/companies/companies.service.ts
  src/modules/companies/dto/get-company-response.dto.ts
  test/support/generator/get-company-generator.ts
Labels: Type: chore

#1189 chore(main): release 1.25.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#1198 chore(deps): dependencies updates
  package-lock.json
  package.json
Labels: Type: chore

#1210 chore(deps): dependencies updates
  package-lock.json
  package.json
Labels: Type: chore

#1211 chore(main): release 1.26.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#1212 fix(error): added globalexceptional handling
  package-lock.json
  src/main.ts
Labels: Type: Fix

#1213 chore(main): release 1.26.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
