Repository UK-Export-Finance/mdm-api, pull requests merged in 2025-10, with the labels that each got.

#1571 chore(merge): merge main into feat/FN-3543/integrate-with-ods
  .github/actions/acr/action.yml
  .github/actions/notify/action.yml
  .github/workflows/deployment.yml
  .github/workflows/github.yml
  .github/workflows/lint.yml
  .github/workflows/pr.yml
  .github/workflows/publish.yml
  .github/workflows/purge.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
  .gitignore
  .markdownlint.json
  .markdownlintignore
  .prettierrc.json
  .release-please-manifest.json
  CHANGELOG.md
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/constants/examples/examples.constant.ts
  src/constants/index.ts
  src/modules/customers/customers.controller.test.ts
  src/modules/customers/customers.service.test.ts
  src/modules/customers/customers.service.ts
  src/modules/customers/dto/create-customer.dto.ts
  src/modules/customers/dto/dtfs-customer.dto.ts
  src/modules/customers/dto/get-customers-response.dto.ts
  src/modules/informatica/dto/get-customers-informatica-response.dto.ts
  src/modules/informatica/informatica.service.test.ts
  src/modules/informatica/informatica.service.ts
  src/modules/salesforce/salesforce.service.ts
  test/customers/post-customers.api-test.ts
  test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
  test/support/generator/get-customers-generator.ts
Labels: Type: chore

#1590 chore(main): release 1.33.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#1596 chore(docs): update README.md
  README.md
Labels: Type: chore, Type: Docs
