Repository UK-Export-Finance/mdm-api, pull requests merged in 2025-07, with the labels that each got.

#1416 feat(GIFT-12948): get business centres from ods
  src/constants/business-centre.constant.ts
  src/constants/index.ts
  src/helpers/convert-string-to-buffer.ts
  src/helpers/date-formatter.helper.test.ts
  src/helpers/get-int-config.helper.test.ts
  src/helpers/get-int-config.ts
  src/helpers/index.ts
  src/helpers/map-business-centres.test.ts
  src/helpers/map-business-centres.ts
  src/helpers/redact-strings-in-log-args.helper.test.ts
  src/helpers/regex.helper.test.ts
  src/helpers/regex.helper.ts
  src/helpers/response-status.helper.test.ts
  src/modules/ods/dto/get-ods-business-centre-mapped-response.dto.ts
  src/modules/ods/dto/get-ods-business-centre-response.dto.ts
  src/modules/ods/dto/index.ts
  src/modules/ods/dto/ods-payloads.dto.ts
  src/modules/ods/ods.controller.test.ts
  src/modules/ods/ods.controller.ts
  src/modules/ods/ods.service-findCustomer.test.ts
  src/modules/ods/ods.service-findDeal.test.ts
  src/modules/ods/ods.service-getBusinessCentres.test.ts
  src/modules/ods/ods.service.test.ts
  src/modules/ods/ods.service.ts
  test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
  test/ods/ods.business-centres.api-test.ts
  test/ods/ods.customers.api-test.ts
  test/ods/ods.deal.api-test.ts
Labels: Type: chore, Type: Docs, Type: Feature

#1436 chore(deps): bumps
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
Labels: Type: chore

#1448 feat(GIFT-13480): ods endpoint versioning
  .env.sample
  docker-compose.yml
  src/config/app.config.test.ts
  src/config/app.config.ts
  src/constants/application.constant.ts
  src/constants/index.ts
  src/modules/companies/companies.controller.ts
  src/modules/currencies/currencies.controller.ts
  src/modules/exposure-period/exposure-period.controller.ts
  src/modules/geospatial/geospatial.controller.ts
  src/modules/interest-rates/interest-rates.controller.ts
  src/modules/markets/markets.controller.ts
  src/modules/ods/ods.controller.ts
  src/modules/premium-schedules/premium-schedules.controller.ts
  src/modules/sector-industries/sector-industries.controller.ts
  test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
  test/ods/ods.business-centres.api-test.ts
  test/ods/ods.customers.api-test.ts
  test/ods/ods.deal.api-test.ts
  test/support/environment-variables.ts
Labels: Type: chore, Type: Feature

#1451 feat(GIFT-13528): get product configuration endpoint
  docker-compose.yml
  src/config/app.config.test.ts
  src/config/app.config.ts
  src/constants/dom.constant.ts
  src/constants/index.ts
  src/modules/dom/dom.controller.test.ts
  src/modules/dom/dom.controller.ts
  src/modules/dom/dom.module.ts
  src/modules/dom/dom.service.test.ts
  src/modules/dom/dom.service.ts
  src/modules/dom/dto/get-dom-product-configuration-response.dto.ts
  src/modules/dom/dto/index.ts
  src/modules/mdm.module.ts
  src/modules/ods/ods.controller.ts
  test/dom/dom-product-configurations.api-test.ts
  test/ods/ods.business-centres.api-test.ts
  test/ods/ods.customers.api-test.ts
  test/ods/ods.deal.api-test.ts
  test/support/environment-variables.ts
Labels: Type: chore, Type: Feature
